// Code generated by go-swagger; DO NOT EDIT.

/*
Package restapi Shortener API
This is a simple API for Shortener URL


    Schemes:
      http
    Host: localhost:8080
    BasePath: /api/v1
    Version: 1.0.0
    License: Apache 2.0 http://www.apache.org/licenses/LICENSE-2.0.html
    Contact: <syrchikov_max@mail.ru>

    Consumes:
    - application/json

    Produces:
    - application/json

swagger:meta
*/
package restapi
