DROP DATABASE IF EXISTS `shortener`;
CREATE DATABASE IF NOT EXISTS `shortener`;
USE `shortener`;

DROP TABLE IF EXISTS `user`;
CREATE TABLE IF NOT EXISTS `user` (
  `id` INT(11) UNSIGNED NOT NULL AUTO_INCREMENT,
  `username` VARCHAR(60) UNIQUE NOT NULL,
  `hash` CHAR(60) NOT NULL,
  `email` VARCHAR(100) UNIQUE NOT NULL,
  `createdAt` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updatedAt` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

DROP TABLE IF EXISTS `link`;
CREATE TABLE IF NOT EXISTS `link` (
  `id` INT(11) UNSIGNED NOT NULL AUTO_INCREMENT,
  `userId` INT(11) UNSIGNED NOT NULL,
  `shortUrl` VARCHAR(10) UNIQUE NOT NULL,
  `fullUrl` VARCHAR(1000) NOT NULL,
  `clicks` INT(11) UNSIGNED NOT NULL DEFAULT 0,
  `createdAt` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updatedAt` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  FOREIGN KEY (`userId`) REFERENCES `shortener`.`user`(`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

INSERT `shortener`.`user` SET username='123', hash='fdgff', email='1232';
INSERT `shortener`.`link` SET shortUrl='jfrf67rf', fullUrl='http://vk.com', userId=1;