DROP DATABASE IF EXISTS `shortener`;
CREATE DATABASE IF NOT EXISTS `shortener`;
USE `shortener`;

DROP TABLE IF EXISTS `user`;
CREATE TABLE IF NOT EXISTS `user` (
  `id` INT(11) UNSIGNED NOT NULL AUTO_INCREMENT,
  `username` VARCHAR(60) UNIQUE NOT NULL,
  `hash` CHAR(64) NOT NULL,
  `email` VARCHAR(100) UNIQUE NOT NULL,
  `timezone` VARCHAR(40) DEFAULT 'Europe/Moscow',
  `language` VARCHAR(5) DEFAULT 'ru_RU',
  `createdAt` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updatedAt` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;