// Code generated by go-swagger; DO NOT EDIT.

package link

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	errors "github.com/go-openapi/errors"
	middleware "github.com/go-openapi/runtime/middleware"
	strfmt "github.com/go-openapi/strfmt"
	swag "github.com/go-openapi/swag"
	validate "github.com/go-openapi/validate"
)

// CreateShortLinkHandlerFunc turns a function with the right signature into a create short link handler
type CreateShortLinkHandlerFunc func(CreateShortLinkParams, interface{}) middleware.Responder

// Handle executing the request and returning a response
func (fn CreateShortLinkHandlerFunc) Handle(params CreateShortLinkParams, principal interface{}) middleware.Responder {
	return fn(params, principal)
}

// CreateShortLinkHandler interface for that can handle valid create short link params
type CreateShortLinkHandler interface {
	Handle(CreateShortLinkParams, interface{}) middleware.Responder
}

// NewCreateShortLink creates a new http.Handler for the create short link operation
func NewCreateShortLink(ctx *middleware.Context, handler CreateShortLinkHandler) *CreateShortLink {
	return &CreateShortLink{Context: ctx, Handler: handler}
}

/*CreateShortLink swagger:route POST /users/me/shorten_urls Link createShortLink

Creating a new short link

*/
type CreateShortLink struct {
	Context *middleware.Context
	Handler CreateShortLinkHandler
}

func (o *CreateShortLink) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		r = rCtx
	}
	var Params = NewCreateShortLinkParams()

	uprinc, aCtx, err := o.Context.Authorize(r, route)
	if err != nil {
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}
	if aCtx != nil {
		r = aCtx
	}
	var principal interface{}
	if uprinc != nil {
		principal = uprinc
	}

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params, principal) // actually handle the request

	o.Context.Respond(rw, r, route.Produces, route, res)

}

// CreateShortLinkBody create short link body
// swagger:model CreateShortLinkBody
type CreateShortLinkBody struct {

	// Full link to some site
	// Required: true
	URL *string `json:"url"`
}

// Validate validates this create short link body
func (o *CreateShortLinkBody) Validate(formats strfmt.Registry) error {
	var res []error

	if err := o.validateURL(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (o *CreateShortLinkBody) validateURL(formats strfmt.Registry) error {

	if err := validate.Required("body"+"."+"url", "body", o.URL); err != nil {
		return err
	}

	return nil
}

// MarshalBinary interface implementation
func (o *CreateShortLinkBody) MarshalBinary() ([]byte, error) {
	if o == nil {
		return nil, nil
	}
	return swag.WriteJSON(o)
}

// UnmarshalBinary interface implementation
func (o *CreateShortLinkBody) UnmarshalBinary(b []byte) error {
	var res CreateShortLinkBody
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*o = res
	return nil
}
