// Code generated by go-swagger; DO NOT EDIT.

package link

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	middleware "github.com/go-openapi/runtime/middleware"
)

// GetLinkHandlerFunc turns a function with the right signature into a get link handler
type GetLinkHandlerFunc func(GetLinkParams, interface{}) middleware.Responder

// Handle executing the request and returning a response
func (fn GetLinkHandlerFunc) Handle(params GetLinkParams, principal interface{}) middleware.Responder {
	return fn(params, principal)
}

// GetLinkHandler interface for that can handle valid get link params
type GetLinkHandler interface {
	Handle(GetLinkParams, interface{}) middleware.Responder
}

// NewGetLink creates a new http.Handler for the get link operation
func NewGetLink(ctx *middleware.Context, handler GetLinkHandler) *GetLink {
	return &GetLink{Context: ctx, Handler: handler}
}

/*GetLink swagger:route GET /shorten_urls/{hash} Link getLink

Get link for redirect

*/
type GetLink struct {
	Context *middleware.Context
	Handler GetLinkHandler
}

func (o *GetLink) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		r = rCtx
	}
	var Params = NewGetLinkParams()

	uprinc, aCtx, err := o.Context.Authorize(r, route)
	if err != nil {
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}
	if aCtx != nil {
		r = aCtx
	}
	var principal interface{}
	if uprinc != nil {
		principal = uprinc
	}

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params, principal) // actually handle the request

	o.Context.Respond(rw, r, route.Produces, route, res)

}
