// Code generated by go-swagger; DO NOT EDIT.

package link

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	models "shortener-api/models"
)

// RemoveLinkNoContentCode is the HTTP code returned for type RemoveLinkNoContent
const RemoveLinkNoContentCode int = 204

/*RemoveLinkNoContent NoContent

swagger:response removeLinkNoContent
*/
type RemoveLinkNoContent struct {
}

// NewRemoveLinkNoContent creates RemoveLinkNoContent with default headers values
func NewRemoveLinkNoContent() *RemoveLinkNoContent {

	return &RemoveLinkNoContent{}
}

// WriteResponse to the client
func (o *RemoveLinkNoContent) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(204)
}

// RemoveLinkUnauthorizedCode is the HTTP code returned for type RemoveLinkUnauthorized
const RemoveLinkUnauthorizedCode int = 401

/*RemoveLinkUnauthorized Authentication information is missing or invalid

swagger:response removeLinkUnauthorized
*/
type RemoveLinkUnauthorized struct {
	/*

	 */
	WWWAuthenticate string `json:"WWW_Authenticate"`

	/*
	  In: Body
	*/
	Payload *models.Error `json:"body,omitempty"`
}

// NewRemoveLinkUnauthorized creates RemoveLinkUnauthorized with default headers values
func NewRemoveLinkUnauthorized() *RemoveLinkUnauthorized {

	return &RemoveLinkUnauthorized{}
}

// WithWWWAuthenticate adds the wWWAuthenticate to the remove link unauthorized response
func (o *RemoveLinkUnauthorized) WithWWWAuthenticate(wWWAuthenticate string) *RemoveLinkUnauthorized {
	o.WWWAuthenticate = wWWAuthenticate
	return o
}

// SetWWWAuthenticate sets the wWWAuthenticate to the remove link unauthorized response
func (o *RemoveLinkUnauthorized) SetWWWAuthenticate(wWWAuthenticate string) {
	o.WWWAuthenticate = wWWAuthenticate
}

// WithPayload adds the payload to the remove link unauthorized response
func (o *RemoveLinkUnauthorized) WithPayload(payload *models.Error) *RemoveLinkUnauthorized {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the remove link unauthorized response
func (o *RemoveLinkUnauthorized) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *RemoveLinkUnauthorized) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	// response header WWW_Authenticate

	wWWAuthenticate := o.WWWAuthenticate
	if wWWAuthenticate != "" {
		rw.Header().Set("WWW_Authenticate", wWWAuthenticate)
	}

	rw.WriteHeader(401)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// RemoveLinkNotFoundCode is the HTTP code returned for type RemoveLinkNotFound
const RemoveLinkNotFoundCode int = 404

/*RemoveLinkNotFound The specified resource was not found

swagger:response removeLinkNotFound
*/
type RemoveLinkNotFound struct {

	/*
	  In: Body
	*/
	Payload *models.Error `json:"body,omitempty"`
}

// NewRemoveLinkNotFound creates RemoveLinkNotFound with default headers values
func NewRemoveLinkNotFound() *RemoveLinkNotFound {

	return &RemoveLinkNotFound{}
}

// WithPayload adds the payload to the remove link not found response
func (o *RemoveLinkNotFound) WithPayload(payload *models.Error) *RemoveLinkNotFound {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the remove link not found response
func (o *RemoveLinkNotFound) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *RemoveLinkNotFound) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(404)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
