// Code generated by go-swagger; DO NOT EDIT.

package link

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	middleware "github.com/go-openapi/runtime/middleware"
)

// RemoveLinkHandlerFunc turns a function with the right signature into a remove link handler
type RemoveLinkHandlerFunc func(RemoveLinkParams, interface{}) middleware.Responder

// Handle executing the request and returning a response
func (fn RemoveLinkHandlerFunc) Handle(params RemoveLinkParams, principal interface{}) middleware.Responder {
	return fn(params, principal)
}

// RemoveLinkHandler interface for that can handle valid remove link params
type RemoveLinkHandler interface {
	Handle(RemoveLinkParams, interface{}) middleware.Responder
}

// NewRemoveLink creates a new http.Handler for the remove link operation
func NewRemoveLink(ctx *middleware.Context, handler RemoveLinkHandler) *RemoveLink {
	return &RemoveLink{Context: ctx, Handler: handler}
}

/*RemoveLink swagger:route DELETE /users/me/shorten_urls/{hash} Link removeLink

Remove short link

*/
type RemoveLink struct {
	Context *middleware.Context
	Handler RemoveLinkHandler
}

func (o *RemoveLink) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		r = rCtx
	}
	var Params = NewRemoveLinkParams()

	uprinc, aCtx, err := o.Context.Authorize(r, route)
	if err != nil {
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}
	if aCtx != nil {
		r = aCtx
	}
	var principal interface{}
	if uprinc != nil {
		principal = uprinc
	}

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params, principal) // actually handle the request

	o.Context.Respond(rw, r, route.Produces, route, res)

}
